export const lightTheme = {
  colors: {
    background: '#ffffff',
    navbarBackground: '#32cd32',
    modalBackground: 'rgba(255, 255, 255, 0.7)',
    loginInputBackground: '#f4f4f4',
    loginInputText: '#919191',
    btnPrimaryBackground: '#32cd32',
    btnPrimaryText: '#ffffff',
    btnPrimaryBorder: '#ffffff',
    btnHoverBackground: '#ffffff',
    btnHoverText: '#32cd32',
    btnHoverBorder: '#32cd32',
    btnDisabledBackground: '#d9d9d9',
    btnDisabledText: '#ffffff',
    toggleBorder: '#b0b0b0',
    toggleSwitch: '#ffffff',
    toggleEnabledBackground: '#32cd32',
    toggleDisabledBackground: '#d9d9d9',
    inputBackground: '#ffffff',
    inputText: '#000000',
    inputBorder: '#b0b0b0',
    containerBackground: '#f9f9f9',
    containerText: '#000000',
    containerBorder: '#b0b0b0',
    checkboxBackground: '#ffffff',
    checkboxBorder: '#b0b0b0',
    checkboxCheck: '#28a7ff',
  },
};

export const darkTheme = {
  colors: {
    background: '#ffffff',
    navbarBackground: '#32cd32',
    modalBackground: 'rgba(255, 255, 255, 0.7)',
    loginInputBackground: '#f4f4f4',
    loginInputText: '#919191',
    btnPrimaryBackground: '#32cd32',
    btnPrimaryText: '#ffffff',
    btnPrimaryBorder: '#ffffff',
    btnHoverBackground: '#ffffff',
    btnHoverText: '#32cd32',
    btnHoverBorder: '#32cd32',
    btnDisabledBackground: '#d9d9d9',
    btnDisabledText: '#ffffff',
    toggleBorder: '#b0b0b0',
    toggleSwitch: '#ffffff',
    toggleEnabledBackground: '#32cd32',
    toggleDisabledBackground: '#d9d9d9',
    inputBackground: '#ffffff',
    inputText: '#000000',
    inputBorder: '#b0b0b0',
    containerBackground: '#f9f9f9',
    containerText: '#000000',
    containerBorder: '#b0b0b0',
    checkboxBackground: '#ffffff',
    checkboxBorder: '#b0b0b0',
    checkboxCheck: '#28a7ff',
  },
};

export type ThemeType = typeof lightTheme;
